name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    name: Build
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Restore NuGet packages - .NET Standard
      run: nuget restore BugGuardian.AspNetCore/BugGuardian.AspNetCore.csproj

    - name: Build the Solution - .NET Standard
      run: msbuild BugGuardian.AspNetCore/BugGuardian.AspNetCore.csproj /p:Configuration=Release

    - name: Restore NuGet packages - .NET Full Framework
      run: nuget restore BugGuardian.AspNetCore.FullFxOnly.sln

    - name: Build the Solution - .NET Full Framework
      run: msbuild BugGuardian.AspNetCore.FullFxOnly.sln /p:Configuration=Release

