name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  BuildNetStandard:
    name: Build .NET Standard 
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore BugGuardian.AspNetCore/BugGuardian.AspNetCore.csproj

    - name: Build the Solution
      run: msbuild BugGuardian.AspNetCore/BugGuardian.AspNetCore.csproj /p:Configuration=Release
    
  BuildNetFullFX:
    name: Build .NET Full Framework
    runs-on: [windows-latest]    
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore BugGuardian.AspNetCore.FullFxOnly.sln

    - name: Build the Solution
      run: msbuild BugGuardian.AspNetCore.FullFxOnly.sln /p:Configuration=Release

